#! /usr/bin/env bash

function parser {
    echo ">> Generating Parser"
    jison src/grammar/soundlang.jison -o src/generated/jison-parser.js -m commonjs
}

function generate {
    echo ">> Generating Demos"
    ./scripts/progbuild.py ./src/demos ./src/generated
    echo ">> Generating Tutorials"
    ./scripts/progbuild.py ./src/tutorials ./src/generated
}

function buildjs {
    echo ">> Building JavaScript"
    browserify ./src/main.jsx --extension=jsx -t [ babelify --presets [ react es2015 ] --ignore "codemirror" ] -o ./dist/app.js
}

function statics {
    echo ">> Handling Statics"
    cp -r ./html/* ./dist/
    cat ./style/*.css > ./dist/style.css
}

function build {
    echo ">> Building App"
    parser
    generate
    buildjs
    statics
}

function clean {
    echo ">> Cleaning"
    rm -rf ./dist/* ./src/generated/*
}

function test {
    echo ">> Testing"
    nodeunit tests
}

function serve {
    echo ">> Serve"
    http-server ./dist
}

function ghpage {
    echo ">> Build Github Pages"

    declare -a files=( "app.js" "index.html" "style.css" "favicon.ico" )
    build

    git checkout gh-pages

    cp -r ./dist/* .;

    for f in "${files[@]}"
    do
        if [ -e "$f" ]; then
            echo "Adding $f"
            git add "$f"
        fi
    done

    git ci -m 'Updating pages'
    git push origin gh-pages

    if [ "$CREATE_BRANCH" == "y" ]; then
        git clean -dfx
    fi

    git checkout master

}

function watch {
    echo ">> Watch"
    watchify ./src/main.js -t babelify -o ./dist/app.js
}

